name: Windows Build & Release

on:
  push:
    branches:
      - master  # 仅在 main 分支触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Pre-install vcpkg
      shell: bash
      run: git clone --depth 1 https://github.com/microsoft/vcpkg.git

    - name: Restore vcpkg cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg/installed
          ${{ github.workspace }}/vcpkg/downloads
        key: vcpkg-windows-${{ hashFiles('.github/workflows/build-tests.yml') }}
        restore-keys: |
          vcpkg-windows-

    - name: Install optional dependencies
      shell: bash
      run: |
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install pkgconf zlib libqrencode zint
        echo "TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.2.*'
        install-deps: 'true'
        archives: 'qtbase qtsvg qttools icu qttranslations'

    - name: Set build directory
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${{ env.TOOLCHAIN_FILE }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Run tests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release

    - name: Upload executables to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/glabels/Release/glabels-qt.exe
          build/glabels-batch/Release/glabels-batch-qt.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
